export const FETCH_IPFS_FILE_START = 'FETCH_IPFS_FILE_START';
export const FETCH_IPFS_FILE_SUCCESS = 'FETCH_IPFS_FILE_SUCCESS';
export const FETCH_IPFS_FILE_FAILED = 'FETCH_IPFS_FILE_FAILED';
export const SEND_FILE_IPFS_START = 'SEND_FILE_IPFS_START';
export const SEND_FILE_IPFS_SUCCESS = 'SEND_FILE_IPFS_SUCCESS';
export const SEND_FILE_IPFS_FAILED = 'SEND_FILE_IPFS_FAILED';
