export const FETCH_CONTRACTS_START = 'FETCH_CONTRACTS_START';
export const FETCH_CONTRACTS_SUCCESS = 'FETCH_CONTRACTS_SUCCESS';
export const FETCH_CONTRACTS_FAILED = 'FETCH_CONTRACTS_FAILDED';
export const CHANGE_CLIENT_FILTER = 'CHANGE_CLIENT_FILTER';
export const CHANGE_EXECUTER_FILTER = 'CHANGE_EXECUTER_FILTER';
export const CHANGE_STATUS_FILTER = 'CHANGE_STATUS_FILTER';
