export const FETCH_USERINFO_START = 'FETCH_USERINFO_START';
export const FETCH_USERINFO_SUCCESS = 'FETCH_USERINFO_SUCCESS';
export const FETCH_USERINFO_FAILED = 'FETCH_USERINFO_FAILED';
export const UPDATE_USERINFO_START = 'UPDATE_USERINFO_START';
export const UPDATE_USERINFO_SUCCESS = 'UPDATE_USERINFO_SUCCESS';
export const UPDATE_USERINFO_FAILED = 'UPDATE_USERINFO_FAILED';
